
-----------------����------------------
--���������� ������̺� �� �������� ����
BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/
--���������� ��� ������ ����
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/
--���������� ��� �� ����
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
-------------------------------------




-- ���̺� ������ ���踦 ����Ͽ� �� ���� �����ص� ������ �߻����� �ʰ� ���ĵǾ����ϴ�.

-- DEPT Table Create SQL
CREATE TABLE DEPT
(
    DEPT_NUM     INT              NOT NULL, 
    DEPT_NAME    VARCHAR2(100)    NOT NULL, 
    CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NUM)
)
/

COMMENT ON TABLE DEPT IS '�μ�'
/

COMMENT ON COLUMN DEPT.DEPT_NUM IS '�μ���ȣPS'
/

COMMENT ON COLUMN DEPT.DEPT_NAME IS '�μ��̸�'
/


-- DEPT Table Create SQL
CREATE TABLE GRADE
(
    GRADE_NUM     INT              NOT NULL, 
    GRADE_NAME    VARCHAR2(100)    NOT NULL, 
    CONSTRAINT GRADE_PK PRIMARY KEY (GRADE_NUM)
)
/

COMMENT ON TABLE GRADE IS '����'
/

COMMENT ON COLUMN GRADE.GRADE_NUM IS '���޹�ȣPS'
/

COMMENT ON COLUMN GRADE.GRADE_NAME IS '����'
/


-- DEPT Table Create SQL
CREATE TABLE EMPLOYEE
(
    EMP_NUM        VARCHAR2(50)     NOT NULL, 
    EMP_PWD        VARCHAR2(200)    NOT NULL, 
    EMP_NAME       VARCHAR2(20)     NOT NULL, 
    EMP_EMAIL      VARCHAR2(100)    NULL, 
    EMP_GENDER     VARCHAR2(10)     NULL, 
    EMP_BIRTH      DATE             NULL, 
    EMP_PHONE      VARCHAR2(20)     NULL, 
    EMP_ADDRESS    VARCHAR2(500)    NULL, 
    GRADE_NUM      INT              NOT NULL, 
    DEPT_NUM       INT              NOT NULL, 
    EMP_SALARY     INT              NOT NULL, 
    ENROLL_DATE    DATE             NOT NULL, 
    RESIGN_DATE    DATE             DEFAULT NULL NULL, 
    EMP_STATUS     VARCHAR2(20)     DEFAULT 'Y' NOT NULL, 
    EMP_ACCOUNT    VARCHAR2(100)    NULL, 
    EMP_BANK       VARCHAR2(100)    NULL, 
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_NUM)
)
/

COMMENT ON TABLE EMPLOYEE IS '����'
/

COMMENT ON COLUMN EMPLOYEE.EMP_NUM IS '�����ȣPST'
/

COMMENT ON COLUMN EMPLOYEE.EMP_PWD IS '��й�ȣ'
/

COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '�̸�'
/

COMMENT ON COLUMN EMPLOYEE.EMP_EMAIL IS '�̸���'
/

COMMENT ON COLUMN EMPLOYEE.EMP_GENDER IS '����'
/

COMMENT ON COLUMN EMPLOYEE.EMP_BIRTH IS '�������'
/

COMMENT ON COLUMN EMPLOYEE.EMP_PHONE IS '��ȭ��ȣ'
/

COMMENT ON COLUMN EMPLOYEE.EMP_ADDRESS IS '�ּ�'
/

COMMENT ON COLUMN EMPLOYEE.GRADE_NUM IS '���޹�ȣF'
/

COMMENT ON COLUMN EMPLOYEE.DEPT_NUM IS '�μ���ȣF'
/

COMMENT ON COLUMN EMPLOYEE.EMP_SALARY IS '����'
/

COMMENT ON COLUMN EMPLOYEE.ENROLL_DATE IS '�Ի���'
/

COMMENT ON COLUMN EMPLOYEE.RESIGN_DATE IS '�����'
/

COMMENT ON COLUMN EMPLOYEE.EMP_STATUS IS '����YN'
/

COMMENT ON COLUMN EMPLOYEE.EMP_ACCOUNT IS '�޿����ɰ���'
/

COMMENT ON COLUMN EMPLOYEE.EMP_BANK IS '�޿���������'
/

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_GRADE_NUM_GRADE_GR FOREIGN KEY (GRADE_NUM)
        REFERENCES GRADE (GRADE_NUM)
/

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPT_NUM_DEPT_DEPT FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT UC_EMP_EMAIL UNIQUE (EMP_EMAIL)
/

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT UC_EMP_ACCOUNT UNIQUE (EMP_ACCOUNT)
/


-- DEPT Table Create SQL
CREATE TABLE CONFIRM
(
    CONFIRM_NUM      VARCHAR2(50)    NOT NULL, 
    CONFIRM_EMP1     VARCHAR2(50)    NOT NULL, 
    CONFIRM_EMP2     VARCHAR2(50)    NULL, 
    CONFIRM_EMP3     VARCHAR2(50)    NULL, 
    CONFIRM_EMP4     VARCHAR2(50)    NULL, 
    CONFIRM_DATE1    DATE            NOT NULL, 
    CONFIRM_DATE2    DATE            NULL, 
    CONFIRM_DATE3    DATE            NULL, 
    CONFIRM_DATE4    DATE            NULL, 
    CONSTRAINT CONFIRM_PK PRIMARY KEY (CONFIRM_NUM)
)
/

COMMENT ON TABLE CONFIRM IS '����'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_NUM IS '������ȣPST'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_EMP1 IS '����1F'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_EMP2 IS '����2F'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_EMP3 IS '����3F'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_EMP4 IS '����4F'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_DATE1 IS '����1�Ͻ�'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_DATE2 IS '����2�Ͻ�'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_DATE3 IS '����3�Ͻ�'
/

COMMENT ON COLUMN CONFIRM.CONFIRM_DATE4 IS '����4�Ͻ�'
/

ALTER TABLE CONFIRM
    ADD CONSTRAINT FK_CONFIRM_CONFIRM_EMP1_EMPLOY FOREIGN KEY (CONFIRM_EMP1)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE CONFIRM
    ADD CONSTRAINT FK_CONFIRM_CONFIRM_EMP2_EMPLOY FOREIGN KEY (CONFIRM_EMP2)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE CONFIRM
    ADD CONSTRAINT FK_CONFIRM_CONFIRM_EMP3_EMPLOY FOREIGN KEY (CONFIRM_EMP3)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE CONFIRM
    ADD CONSTRAINT FK_CONFIRM_CONFIRM_EMP4_EMPLOY FOREIGN KEY (CONFIRM_EMP4)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE APPROVAL
(
    APPROVAL_NUM     VARCHAR2(50)    NOT NULL, 
    APPROVAL_DATE    VARCHAR2(20)    NOT NULL, 
    DOC_NUM          VARCHAR2(20)    NOT NULL, 
    CONSTRAINT APPROVAL_PK PRIMARY KEY (APPROVAL_NUM)
)
/

COMMENT ON TABLE APPROVAL IS '���ι�ȣ'
/

COMMENT ON COLUMN APPROVAL.APPROVAL_NUM IS '���ι�ȣPST'
/

COMMENT ON COLUMN APPROVAL.APPROVAL_DATE IS '�����Ͻ�'
/

COMMENT ON COLUMN APPROVAL.DOC_NUM IS '������ȣ'
/


-- DEPT Table Create SQL
CREATE TABLE PARTNER
(
    PARTNER_NUM        VARCHAR2(50)      NOT NULL, 
    PARTNER_NAME       VARCHAR2(200)     NOT NULL, 
    PARTNER_PHONE      VARCHAR2(200)     NULL, 
    PARTNER_FAX        VARCHAR2(200)     NULL, 
    PARTNER_ADDRESS    VARCHAR2(1000)    NULL, 
    BUSSINESS_NUM      VARCHAR2(100)     NOT NULL, 
    PARTNER_EMP        VARCHAR2(200)     NULL, 
    CONSTRAINT PARTNER_PK PRIMARY KEY (PARTNER_NUM)
)
/

COMMENT ON TABLE PARTNER IS '�ŷ�ó'
/

COMMENT ON COLUMN PARTNER.PARTNER_NUM IS '�ŷ�ó��ȣPST'
/

COMMENT ON COLUMN PARTNER.PARTNER_NAME IS '�ŷ�ó�̸�'
/

COMMENT ON COLUMN PARTNER.PARTNER_PHONE IS '�ŷ�ó��ǥ��ȣ'
/

COMMENT ON COLUMN PARTNER.PARTNER_FAX IS '�ŷ�ó�ѽ�'
/

COMMENT ON COLUMN PARTNER.PARTNER_ADDRESS IS '�ŷ�ó�ּ�'
/

COMMENT ON COLUMN PARTNER.BUSSINESS_NUM IS '�ŷ�ó����ڹ�ȣ'
/

COMMENT ON COLUMN PARTNER.PARTNER_EMP IS '�ŷ�ó�����'
/


-- DEPT Table Create SQL
CREATE TABLE CHAT_ROOM
(
    CHAT_ROOM    VARCHAR2(50)     NOT NULL, 
    CHAT_NAME    VARCHAR2(200)    NULL, 
    CONSTRAINT CHAT_ROOM_PK PRIMARY KEY (CHAT_ROOM)
)
/

COMMENT ON TABLE CHAT_ROOM IS 'ä�ù�,����'
/

COMMENT ON COLUMN CHAT_ROOM.CHAT_ROOM IS '���ȣPST'
/

COMMENT ON COLUMN CHAT_ROOM.CHAT_NAME IS '���̸�'
/


-- DEPT Table Create SQL
CREATE TABLE PAYMENT
(
    PAY_NUM        VARCHAR2(50)     NOT NULL, 
    PAY_PRICE      INT              NOT NULL, 
    PAY_AMOUNT     INT              NOT NULL, 
    PARTNER_NUM    VARCHAR2(50)     NOT NULL, 
    PAY_DATE       DATE             NOT NULL, 
    PAY_METHOD     VARCHAR2(50)     NOT NULL, 
    PAY_BANK       VARCHAR2(100)    NULL, 
    CONSTRAINT PAYMENT_PK PRIMARY KEY (PAY_NUM)
)
/

COMMENT ON TABLE PAYMENT IS '��������'
/

COMMENT ON COLUMN PAYMENT.PAY_NUM IS '������ȣPST'
/

COMMENT ON COLUMN PAYMENT.PAY_PRICE IS '�����ݾ�'
/

COMMENT ON COLUMN PAYMENT.PAY_AMOUNT IS '����'
/

COMMENT ON COLUMN PAYMENT.PARTNER_NUM IS '�ŷ�ó��ȣF'
/

COMMENT ON COLUMN PAYMENT.PAY_DATE IS '������'
/

COMMENT ON COLUMN PAYMENT.PAY_METHOD IS '�������'
/

COMMENT ON COLUMN PAYMENT.PAY_BANK IS '��������'
/

ALTER TABLE PAYMENT
    ADD CONSTRAINT FK_PAYMENT_PARTNER_NUM_PARTNER FOREIGN KEY (PARTNER_NUM)
        REFERENCES PARTNER (PARTNER_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE ACCOUNT
(
    ACCOUNT_NUM        VARCHAR2(50)     NOT NULL, 
    ACCOUNT_NAME       VARCHAR2(100)    NOT NULL, 
    ACCOUNT_DESCRIP    VARCHAR2(20)     NOT NULL, 
    ACCOUNT_ALI        VARCHAR2(20)     NOT NULL, 
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_NUM)
)
/

COMMENT ON TABLE ACCOUNT IS '��������'
/

COMMENT ON COLUMN ACCOUNT.ACCOUNT_NUM IS '�����ȣPST'
/

COMMENT ON COLUMN ACCOUNT.ACCOUNT_NAME IS '�����̸�'
/

COMMENT ON COLUMN ACCOUNT.ACCOUNT_DESCRIP IS '��������'
/

COMMENT ON COLUMN ACCOUNT.ACCOUNT_ALI IS '�ڻ��ä�ں�ALE'
/

ALTER TABLE ACCOUNT
    ADD CONSTRAINT UC_ACCOUNT_NAME UNIQUE (ACCOUNT_NAME)
/


-- DEPT Table Create SQL
CREATE TABLE CHAT_JOIN
(
    CHAT_ROOM    VARCHAR2(50)    NOT NULL, 
    CHAT_USER    VARCHAR2(50)    NOT NULL, 
    CHAT_LAST    DATE            NOT NULL, 
    CONSTRAINT CHAT_JOIN_PK PRIMARY KEY (CHAT_ROOM, CHAT_USER)
)
/

COMMENT ON COLUMN CHAT_JOIN.CHAT_ROOM IS '���ȣPF'
/

COMMENT ON COLUMN CHAT_JOIN.CHAT_USER IS '������ȣF'
/

COMMENT ON COLUMN CHAT_JOIN.CHAT_LAST IS '�����������Ͻ�'
/

ALTER TABLE CHAT_JOIN
    ADD CONSTRAINT FK_CHAT_JOIN_CHAT_ROOM_CHAT_RO FOREIGN KEY (CHAT_ROOM)
        REFERENCES CHAT_ROOM (CHAT_ROOM)
/


-- DEPT Table Create SQL
CREATE TABLE DOC_HOLIDAY
(
    HOLI_NUM          VARCHAR2(50)    NOT NULL, 
    DEPT_NUM          INT             NOT NULL, 
    EMP_NUM           VARCHAR2(50)    NOT NULL, 
    HOLI_TYPE         VARCHAR2(20)    NOT NULL, 
    HOLI_APPLY        DATE            NOT NULL, 
    HOLIDAY_START     DATE            NOT NULL, 
    HOLIDAY_END       DATE            NOT NULL, 
    APPROVAL_NUM      VARCHAR2(50)    NULL, 
    CONFIRM_NUM       VARCHAR2(50)    NULL, 
    HOLIDAY_STATUS    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT DOC_HOLIDAY_PK PRIMARY KEY (HOLI_NUM)
)
/

COMMENT ON TABLE DOC_HOLIDAY IS '����_�ް�/����'
/

COMMENT ON COLUMN DOC_HOLIDAY.HOLI_NUM IS '�ް���û��ȣPST'
/

COMMENT ON COLUMN DOC_HOLIDAY.DEPT_NUM IS '�ް���û�μ�F'
/

COMMENT ON COLUMN DOC_HOLIDAY.EMP_NUM IS '��û��F'
/

COMMENT ON COLUMN DOC_HOLIDAY.HOLI_TYPE IS '�ް�Ÿ��APF'
/

COMMENT ON COLUMN DOC_HOLIDAY.HOLI_APPLY IS '�ް���û�Ͻ�'
/

COMMENT ON COLUMN DOC_HOLIDAY.HOLIDAY_START IS '�ް�������'
/

COMMENT ON COLUMN DOC_HOLIDAY.HOLIDAY_END IS '�ް�������'
/

COMMENT ON COLUMN DOC_HOLIDAY.APPROVAL_NUM IS '���ι�ȣF'
/

COMMENT ON COLUMN DOC_HOLIDAY.CONFIRM_NUM IS '������ȣF'
/

COMMENT ON COLUMN DOC_HOLIDAY.HOLIDAY_STATUS IS '����YN'
/

ALTER TABLE DOC_HOLIDAY
    ADD CONSTRAINT FK_DOC_HOLIDAY_DEPT_NUM_DEPT_D FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/

ALTER TABLE DOC_HOLIDAY
    ADD CONSTRAINT FK_DOC_HOLIDAY_EMP_NUM_EMPLOYE FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE DOC_HOLIDAY
    ADD CONSTRAINT FK_DOC_HOLIDAY_CONFIRM_NUM_CON FOREIGN KEY (CONFIRM_NUM)
        REFERENCES CONFIRM (CONFIRM_NUM)
/

ALTER TABLE DOC_HOLIDAY
    ADD CONSTRAINT FK_DOC_HOLIDAY_APPROVAL_NUM_AP FOREIGN KEY (APPROVAL_NUM)
        REFERENCES APPROVAL (APPROVAL_NUM)
/

ALTER TABLE DOC_HOLIDAY
    ADD CONSTRAINT UC_APPROVAL_NUM UNIQUE (APPROVAL_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE PRODUCT
(
    PRODUCT_CODE      varchar2(50)      NOT NULL, 
    PRODUCT_NAME      VARCHAR2(2000)    NOT NULL, 
    PRODUCT_PRICET    INT               NOT NULL, 
    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_CODE)
)
/

COMMENT ON TABLE PRODUCT IS '��ǰ'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_CODE IS '��ǰ�ڵ�PST'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '��ǰ��'
/

COMMENT ON COLUMN PRODUCT.PRODUCT_PRICET IS '��ǰ����'
/


-- DEPT Table Create SQL
CREATE TABLE DOC_DRAFT
(
    DRAFT_NUM         VARCHAR2(50)      NOT NULL, 
    DEPT_NUM          INT               NOT NULL, 
    EMP_NUM           VARCHAR2(50)      NOT NULL, 
    DRAFT_TITLE       VARCHAR2(200)     NOT NULL, 
    DRAFT_CONTENT     VARCHAR2(2000)    NULL, 
    DRAFT_DATE        DATE              NOT NULL, 
    PRESERV_YAER      INT               NOT NULL, 
    EXPIRATE_DATE     DATE              NOT NULL, 
    DRAFT_STATUS      VARCHAR2(20)      DEFAULT 'Y' NOT NULL, 
    DRAFT_COMPLETE    DATE              NULL, 
    APPROVAL_NUM      VARCHAR2(50)      NULL, 
    CONFIRM_NUM       VARCHAR2(50)      NOT NULL, 
    CONSTRAINT DOC_DRAFT_PK PRIMARY KEY (DRAFT_NUM)
)
/

COMMENT ON TABLE DOC_DRAFT IS '����_��ȼ�'
/

COMMENT ON COLUMN DOC_DRAFT.DRAFT_NUM IS '��ȼ���ȣPST'
/

COMMENT ON COLUMN DOC_DRAFT.DEPT_NUM IS '��Ⱥμ�F'
/

COMMENT ON COLUMN DOC_DRAFT.EMP_NUM IS '�����F'
/

COMMENT ON COLUMN DOC_DRAFT.DRAFT_TITLE IS '�������'
/

COMMENT ON COLUMN DOC_DRAFT.DRAFT_CONTENT IS '��ȳ���'
/

COMMENT ON COLUMN DOC_DRAFT.DRAFT_DATE IS '����Ͻ�'
/

COMMENT ON COLUMN DOC_DRAFT.PRESERV_YAER IS '��������'
/

COMMENT ON COLUMN DOC_DRAFT.EXPIRATE_DATE IS '����������'
/

COMMENT ON COLUMN DOC_DRAFT.DRAFT_STATUS IS '����YN'
/

COMMENT ON COLUMN DOC_DRAFT.DRAFT_COMPLETE IS '�Ϸ��Ͻ�'
/

COMMENT ON COLUMN DOC_DRAFT.APPROVAL_NUM IS '���ι�ȣF'
/

COMMENT ON COLUMN DOC_DRAFT.CONFIRM_NUM IS '������ȣF'
/

ALTER TABLE DOC_DRAFT
    ADD CONSTRAINT FK_DOC_DRAFT_DEPT_NUM_DEPT_DEP FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/

ALTER TABLE DOC_DRAFT
    ADD CONSTRAINT FK_DOC_DRAFT_EMP_NUM_EMPLOYEE_ FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE DOC_DRAFT
    ADD CONSTRAINT FK_DOC_DRAFT_CONFIRM_NUM_CONFI FOREIGN KEY (CONFIRM_NUM)
        REFERENCES CONFIRM (CONFIRM_NUM)
/

ALTER TABLE DOC_DRAFT
    ADD CONSTRAINT FK_DOC_DRAFT_APPROVAL_NUM_APPR FOREIGN KEY (APPROVAL_NUM)
        REFERENCES APPROVAL (APPROVAL_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE SCHEDULE_EMP
(
    EMP_NUM             VARCHAR2(50)     NULL, 
    DEPT_NUM            INT              NULL, 
    SCH_EMP_START       DATE             NOT NULL, 
    SCH_EMP_END         DATE             NOT NULL, 
    REGISTER_EMP_NUM    VARCHAR2(50)     NOT NULL, 
    SCH_CONTENT         VARCHAR2(500)    NULL   
)
/

COMMENT ON TABLE SCHEDULE_EMP IS '����'
/

COMMENT ON COLUMN SCHEDULE_EMP.EMP_NUM IS '�����ȣF'
/

COMMENT ON COLUMN SCHEDULE_EMP.DEPT_NUM IS '�μ���ȣF'
/

COMMENT ON COLUMN SCHEDULE_EMP.SCH_EMP_START IS '������'
/

COMMENT ON COLUMN SCHEDULE_EMP.SCH_EMP_END IS '������'
/

COMMENT ON COLUMN SCHEDULE_EMP.REGISTER_EMP_NUM IS '�����'
/

COMMENT ON COLUMN SCHEDULE_EMP.SCH_CONTENT IS '����'
/

ALTER TABLE SCHEDULE_EMP
    ADD CONSTRAINT FK_SCHEDULE_EMP_EMP_NUM_EMPLOY FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE SCHEDULE_EMP
    ADD CONSTRAINT FK_SCHEDULE_EMP_DEPT_NUM_DEPT_ FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE TNA
(
    EMP_NUM       VARCHAR2(50)    NOT NULL, 
    TNA_YEAR      DATE            NOT NULL, 
    TNA_SCORE     NUMBER          NOT NULL, 
    CHARGE_NUM    VARCHAR2(50)    NOT NULL, 
    CONSTRAINT TNA_PK PRIMARY KEY (EMP_NUM, TNA_YEAR)
)
/

COMMENT ON TABLE TNA IS '��������'
/

COMMENT ON COLUMN TNA.EMP_NUM IS '�����ȣPF'
/

COMMENT ON COLUMN TNA.TNA_YEAR IS '�򰡳⵵P'
/

COMMENT ON COLUMN TNA.TNA_SCORE IS '����'
/

COMMENT ON COLUMN TNA.CHARGE_NUM IS 'å����F'
/

ALTER TABLE TNA
    ADD CONSTRAINT FK_TNA_EMP_NUM_EMPLOYEE_EMP_NU FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE TNA
    ADD CONSTRAINT FK_TNA_CHARGE_NUM_EMPLOYEE_EMP FOREIGN KEY (CHARGE_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE NOTICE
(
    NOTICE_NUM         VARCHAR2(50)      NOT NULL, 
    NOTICE_DEPT        INT               NOT NULL, 
    NOTICE_TITLE       VARCHAR2(100)     NOT NULL, 
    NOTICE_CONTENT     VARCHAR2(2000)    NULL, 
    EMP_NUM            VARCHAR2(50)      NOT NULL, 
    NOTICE_DATE        DATE              NOT NULL, 
    NOTICE_MODIFY      DATE              NULL, 
    NOTICE_STATUS      VARCHAR2(20)      DEFAULT 'Y' NOT NULL, 
    NOTICE_ACC_TYPE    INT               NULL, 
    CONSTRAINT NOTICE_PK PRIMARY KEY (NOTICE_NUM)
)
/

COMMENT ON TABLE NOTICE IS '����'
/

COMMENT ON COLUMN NOTICE.NOTICE_NUM IS '������ȣPST'
/

COMMENT ON COLUMN NOTICE.NOTICE_DEPT IS '�����μ���ȣF'
/

COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '��������'
/

COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '��������'
/

COMMENT ON COLUMN NOTICE.EMP_NUM IS '�Խ���F'
/

COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '�����Ͻ�'
/

COMMENT ON COLUMN NOTICE.NOTICE_MODIFY IS '������'
/

COMMENT ON COLUMN NOTICE.NOTICE_STATUS IS '��������YN'
/

COMMENT ON COLUMN NOTICE.NOTICE_ACC_TYPE IS '����ȸ��Ÿ��'
/

ALTER TABLE NOTICE
    ADD CONSTRAINT FK_NOTICE_EMP_NUM_EMPLOYEE_EMP FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE NOTICE
    ADD CONSTRAINT FK_NOTICE_NOTICE_DEPT_DEPT_DEP FOREIGN KEY (NOTICE_DEPT)
        REFERENCES DEPT (DEPT_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE EOTM
(
    EMP_NUM         VARCHAR2(50)      NOT NULL, 
    EOTM_DATE       DATE              NOT NULL, 
    EOTM_CONTNET    VARCHAR2(2000)    NULL, 
    EOTM_SCORE      INT               NOT NULL, 
    CONSTRAINT EOTM_PK PRIMARY KEY (EMP_NUM, EOTM_DATE)
)
/

COMMENT ON TABLE EOTM IS 'EMPLOYEE OF THE MONTH'
/

COMMENT ON COLUMN EOTM.EMP_NUM IS '�����ȣPF'
/

COMMENT ON COLUMN EOTM.EOTM_DATE IS '�Ͻ�P'
/

COMMENT ON COLUMN EOTM.EOTM_CONTNET IS 'Ī������'
/

COMMENT ON COLUMN EOTM.EOTM_SCORE IS '����'
/

ALTER TABLE EOTM
    ADD CONSTRAINT FK_EOTM_EMP_NUM_EMPLOYEE_EMP_N FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE DOC_REQUEST
(
    REQUEST_NUM         VARCHAR2(50)      NOT NULL, 
    DEPT_NUM            INT               NOT NULL, 
    EMP_NUM             VARCHAR2(50)      NOT NULL, 
    REQUEST_TITLE       VARCHAR2(200)     NOT NULL, 
    REQUEST_CONTENT     VARCHAR2(2000)    NULL, 
    REQUEST_DATE        DATE              NOT NULL, 
    PRESERV_YAER        INT               NOT NULL, 
    EXPIRATE_DATE       DATE              NOT NULL, 
    REQUEST_STATUS      VARCHAR2(20)      DEFAULT 'Y' NOT NULL, 
    REQUEST_COMPLETE    DATE              NULL, 
    APPROVAL_NUM        VARCHAR2(50)      NULL, 
    CONFIRM_NUM         VARCHAR2(50)      NULL, 
    CONSTRAINT DOC_REQUEST_PK PRIMARY KEY (REQUEST_NUM)
)
/

COMMENT ON TABLE DOC_REQUEST IS '����_ǰ�Ǽ�'
/

COMMENT ON COLUMN DOC_REQUEST.REQUEST_NUM IS 'ǰ�Ǽ���ȣPST'
/

COMMENT ON COLUMN DOC_REQUEST.DEPT_NUM IS 'ǰ�Ǻμ�F'
/

COMMENT ON COLUMN DOC_REQUEST.EMP_NUM IS 'ǰ����F'
/

COMMENT ON COLUMN DOC_REQUEST.REQUEST_TITLE IS 'ǰ������'
/

COMMENT ON COLUMN DOC_REQUEST.REQUEST_CONTENT IS 'ǰ�ǳ���'
/

COMMENT ON COLUMN DOC_REQUEST.REQUEST_DATE IS 'ǰ���Ͻ�'
/

COMMENT ON COLUMN DOC_REQUEST.PRESERV_YAER IS '��������'
/

COMMENT ON COLUMN DOC_REQUEST.EXPIRATE_DATE IS '����������'
/

COMMENT ON COLUMN DOC_REQUEST.REQUEST_STATUS IS '����YN'
/

COMMENT ON COLUMN DOC_REQUEST.REQUEST_COMPLETE IS '�Ϸ��Ͻ�'
/

COMMENT ON COLUMN DOC_REQUEST.APPROVAL_NUM IS '���ι�ȣF'
/

COMMENT ON COLUMN DOC_REQUEST.CONFIRM_NUM IS '������ȣF'
/

ALTER TABLE DOC_REQUEST
    ADD CONSTRAINT FK_DOC_REQUEST_DEPT_NUM_DEPT_D FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/

ALTER TABLE DOC_REQUEST
    ADD CONSTRAINT FK_DOC_REQUEST_EMP_NUM_EMPLOYE FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE DOC_REQUEST
    ADD CONSTRAINT FK_DOC_REQUEST_CONFIRM_NUM_CON FOREIGN KEY (CONFIRM_NUM)
        REFERENCES CONFIRM (CONFIRM_NUM)
/

ALTER TABLE DOC_REQUEST
    ADD CONSTRAINT FK_DOC_REQUEST_APPROVAL_NUM_AP FOREIGN KEY (APPROVAL_NUM)
        REFERENCES APPROVAL (APPROVAL_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE DOC_EXPENSE
(
    EXPENSE_NUM         VARCHAR2(50)      NOT NULL, 
    DEPT_NUM            INT               NOT NULL, 
    EMP_NUM             VARCHAR2(50)      NOT NULL, 
    EXPENSE_TITLE       VARCHAR2(200)     NOT NULL, 
    EXPENSE_CONTENT     VARCHAR2(2000)    NULL, 
    EXPENSE_DATE        DATE              NOT NULL, 
    PARTNER_NUM         VARCHAR2(50)      NULL, 
    EXPENSE_PRICE       INT               NOT NULL, 
    PRESERV_YEAR        INT               NOT NULL, 
    EXPIRATE_DATE       DATE              NOT NULL, 
    EXPENSE_STAUS       VARCHAR2(20)      DEFAULT 'Y' NOT NULL, 
    EXPENSE_COLPLETE    DATE              NULL, 
    APPROVAL_NUM        VARCHAR2(50)      NULL, 
    CONFIRM_NUM         VARCHAR2(50)      NULL, 
    CONSTRAINT DOC_EXPENSE_PK PRIMARY KEY (EXPENSE_NUM)
)
/

COMMENT ON TABLE DOC_EXPENSE IS '����_�������'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_NUM IS '������ǹ�ȣPST'
/

COMMENT ON COLUMN DOC_EXPENSE.DEPT_NUM IS '������Ǻμ�F'
/

COMMENT ON COLUMN DOC_EXPENSE.EMP_NUM IS '���������F'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_TITLE IS '�����������'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_CONTENT IS '������ǳ���'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_DATE IS '������ǵ���Ͻ�'
/

COMMENT ON COLUMN DOC_EXPENSE.PARTNER_NUM IS '�ŷ�ó��ȣF'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_PRICE IS '�ŷ��ݾ�'
/

COMMENT ON COLUMN DOC_EXPENSE.PRESERV_YEAR IS '��������'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPIRATE_DATE IS '����������'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_STAUS IS '����YN'
/

COMMENT ON COLUMN DOC_EXPENSE.EXPENSE_COLPLETE IS '�Ϸ��Ͻ�'
/

COMMENT ON COLUMN DOC_EXPENSE.APPROVAL_NUM IS '���ι�ȣF'
/

COMMENT ON COLUMN DOC_EXPENSE.CONFIRM_NUM IS '������ȣF'
/

ALTER TABLE DOC_EXPENSE
    ADD CONSTRAINT FK_DOC_EXPENSE_DEPT_NUM_DEPT_D FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/

ALTER TABLE DOC_EXPENSE
    ADD CONSTRAINT FK_DOC_EXPENSE_EMP_NUM_EMPLOYE FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE DOC_EXPENSE
    ADD CONSTRAINT FK_DOC_EXPENSE_PARTNER_NUM_PAR FOREIGN KEY (PARTNER_NUM)
        REFERENCES PARTNER (PARTNER_NUM)
/

ALTER TABLE DOC_EXPENSE
    ADD CONSTRAINT FK_DOC_EXPENSE_CONFIRM_NUM_CON FOREIGN KEY (CONFIRM_NUM)
        REFERENCES CONFIRM (CONFIRM_NUM)
/

ALTER TABLE DOC_EXPENSE
    ADD CONSTRAINT FK_DOC_EXPENSE_APPROVAL_NUM_AP FOREIGN KEY (APPROVAL_NUM)
        REFERENCES APPROVAL (APPROVAL_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE JOURNALIZING
(
    JOURN_NUM       INT               NOT NULL, 
    JOURN_DATE      DATE              NOT NULL, 
    DEBT            VARCHAR2(100)     NULL, 
    DEBT_PRICE      INT               NULL, 
    CREDIT          VARCHAR2(100)     NULL, 
    CREDIT_PRICE    INT               NULL, 
    JOURN_MEMO      VARCHAR2(2000)    NULL, 
    CONSTRAINT JOURNALIZING_PK PRIMARY KEY (JOURN_NUM)
)
/

COMMENT ON TABLE JOURNALIZING IS '�а���'
/

COMMENT ON COLUMN JOURNALIZING.JOURN_NUM IS '�а���ȣPS'
/

COMMENT ON COLUMN JOURNALIZING.JOURN_DATE IS '��¥'
/

COMMENT ON COLUMN JOURNALIZING.DEBT IS '����'
/

COMMENT ON COLUMN JOURNALIZING.DEBT_PRICE IS '�ݾ�'
/

COMMENT ON COLUMN JOURNALIZING.CREDIT IS '�뺯'
/

COMMENT ON COLUMN JOURNALIZING.CREDIT_PRICE IS '�ݾ�'
/

COMMENT ON COLUMN JOURNALIZING.JOURN_MEMO IS '���'
/

ALTER TABLE JOURNALIZING
    ADD CONSTRAINT FK_JOURNALIZING_DEBT_ACCOUNT_A FOREIGN KEY (DEBT)
        REFERENCES ACCOUNT (ACCOUNT_NAME)
/

ALTER TABLE JOURNALIZING
    ADD CONSTRAINT FK_JOURNALIZING_CREDIT_ACCOUNT FOREIGN KEY (CREDIT)
        REFERENCES ACCOUNT (ACCOUNT_NAME)
/


-- DEPT Table Create SQL
CREATE TABLE LICENSE
(
    LICENSE_MANAGE    VARCHAR2(50)     NOT NULL, 
    PRODUCT_NAME      VARCHAR2(200)    NOT NULL, 
    LICENSE_NUM       VARCHAR2(200)    NOT NULL, 
    PAY_NUM           VARCHAR2(50)     NOT NULL, 
    LICENSE_START     DATE             NOT NULL, 
    LICENSE_END       DATE             DEFAULT NULL NULL, 
    LICENSE_UPDATE    DATE             DEFAULT NULL NULL, 
    CONSTRAINT LICENSE_PK PRIMARY KEY (LICENSE_MANAGE)
)
/

COMMENT ON TABLE LICENSE IS '���̼�������'
/

COMMENT ON COLUMN LICENSE.LICENSE_MANAGE IS '������ȣPST'
/

COMMENT ON COLUMN LICENSE.PRODUCT_NAME IS '��ǰ��'
/

COMMENT ON COLUMN LICENSE.LICENSE_NUM IS '���̼�����ȣ'
/

COMMENT ON COLUMN LICENSE.PAY_NUM IS '������ȣF'
/

COMMENT ON COLUMN LICENSE.LICENSE_START IS '��������'
/

COMMENT ON COLUMN LICENSE.LICENSE_END IS '������'
/

COMMENT ON COLUMN LICENSE.LICENSE_UPDATE IS '������'
/

ALTER TABLE LICENSE
    ADD CONSTRAINT FK_LICENSE_PAY_NUM_PAYMENT_PAY FOREIGN KEY (PAY_NUM)
        REFERENCES PAYMENT (PAY_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE FIXTURE
(
    FIXTURE_NUM          VARCHAR2(50)     NOT NULL, 
    FIXTURE_TYPE         VARCHAR2(100)    NOT NULL, 
    FIXTURE_NAME         VARCHAR2(500)    NOT NULL, 
    FIXTURE_BUY          DATE             NOT NULL, 
    DEPT_NUM             INT              NULL, 
    EMP_NUM              VARCHAR2(50)     NULL, 
    FIXTURE_ENDURANCE    INT              NOT NULL, 
    FIXTURE_PAYMENT      VARCHAR2(50)     NULL, 
    CONSTRAINT FIXTURE_PK PRIMARY KEY (FIXTURE_NUM)
)
/

COMMENT ON TABLE FIXTURE IS '��ǰ����'
/

COMMENT ON COLUMN FIXTURE.FIXTURE_NUM IS '��ǰ��ȣPST'
/

COMMENT ON COLUMN FIXTURE.FIXTURE_TYPE IS '��ǰ����'
/

COMMENT ON COLUMN FIXTURE.FIXTURE_NAME IS '��ǰ��'
/

COMMENT ON COLUMN FIXTURE.FIXTURE_BUY IS '��ǰ������'
/

COMMENT ON COLUMN FIXTURE.DEPT_NUM IS '���μ�F'
/

COMMENT ON COLUMN FIXTURE.EMP_NUM IS '�����F'
/

COMMENT ON COLUMN FIXTURE.FIXTURE_ENDURANCE IS '��������'
/

COMMENT ON COLUMN FIXTURE.FIXTURE_PAYMENT IS '��ǰ������ȣ'
/

ALTER TABLE FIXTURE
    ADD CONSTRAINT FK_FIXTURE_DEPT_NUM_DEPT_DEPT_ FOREIGN KEY (DEPT_NUM)
        REFERENCES DEPT (DEPT_NUM)
/

ALTER TABLE FIXTURE
    ADD CONSTRAINT FK_FIXTURE_EMP_NUM_EMPLOYEE_EM FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE FIXTURE
    ADD CONSTRAINT FK_FIXTURE_FIXTURE_PAYMENT_PAY FOREIGN KEY (FIXTURE_PAYMENT)
        REFERENCES PAYMENT (PAY_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE SALARY
(
    EMP_NUM     VARCHAR2(50)    NOT NULL, 
    SAL_YEAR    INT             NOT NULL, 
    SALARY      INT             NOT NULL, 
    CONSTRAINT SALARY_PK PRIMARY KEY (EMP_NUM, SAL_YEAR)
)
/

COMMENT ON TABLE SALARY IS '����'
/

COMMENT ON COLUMN SALARY.EMP_NUM IS '�����ȣPF'
/

COMMENT ON COLUMN SALARY.SAL_YEAR IS '�⵵P'
/

COMMENT ON COLUMN SALARY.SALARY IS '����'
/

ALTER TABLE SALARY
    ADD CONSTRAINT FK_SALARY_EMP_NUM_EMPLOYEE_EMP FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE ATTENDANCE
(
    EMP_NUM     VARCHAR2(50)    NOT NULL, 
    ATT_DATE    DATE            NOT NULL, 
    TIME_ON     DATE            NULL, 
    TIME_OFF    DATE            NULL, 
    CONSTRAINT ATTENDANCE_PK PRIMARY KEY (EMP_NUM, ATT_DATE)
)
/

COMMENT ON TABLE ATTENDANCE IS '�����'
/

COMMENT ON COLUMN ATTENDANCE.EMP_NUM IS '�����ȣPF'
/

COMMENT ON COLUMN ATTENDANCE.ATT_DATE IS '��¥P'
/

COMMENT ON COLUMN ATTENDANCE.TIME_ON IS '��ٽð�'
/

COMMENT ON COLUMN ATTENDANCE.TIME_OFF IS '��ٽð�'
/

ALTER TABLE ATTENDANCE
    ADD CONSTRAINT FK_ATTENDANCE_EMP_NUM_EMPLOYEE FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE HOLIDAY_COUNT
(
    EMP_NUM          VARCHAR2(50)    NOT NULL, 
    HOLIDAY_COUNT    NUMBER          NOT NULL, 
    HOLIDAY_LEFT     NUMBER          NOT NULL, 
    HOLIDAY_YEAR     VARCHAR2(20)    NOT NULL, 
    CONSTRAINT HOLIDAY_COUNT_PK PRIMARY KEY (EMP_NUM)
)
/

COMMENT ON TABLE HOLIDAY_COUNT IS '�ް� ���� ī��Ʈ'
/

COMMENT ON COLUMN HOLIDAY_COUNT.EMP_NUM IS '�����ȣPF'
/

COMMENT ON COLUMN HOLIDAY_COUNT.HOLIDAY_COUNT IS '�ѿ�����'
/

COMMENT ON COLUMN HOLIDAY_COUNT.HOLIDAY_LEFT IS '��������'
/

COMMENT ON COLUMN HOLIDAY_COUNT.HOLIDAY_YEAR IS '�⵵'
/

ALTER TABLE HOLIDAY_COUNT
    ADD CONSTRAINT FK_HOLIDAY_COUNT_EMP_NUM_EMPLO FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE HOLIDAY
(
    APPROVAL_NUM     VARCHAR2(50)    NOT NULL, 
    EMP_NUMNT        VARCHAR2(50)    NOT NULL, 
    HOLIDAY_START    DATE            NOT NULL, 
    HOLIDAY_END      DATE            NOT NULL, 
    CONSTRAINT HOLIDAY_PK PRIMARY KEY (APPROVAL_NUM)
)
/

COMMENT ON TABLE HOLIDAY IS '�ް����'
/

COMMENT ON COLUMN HOLIDAY.APPROVAL_NUM IS '���ι�ȣPF'
/

COMMENT ON COLUMN HOLIDAY.EMP_NUMNT IS '�����ȣF'
/

COMMENT ON COLUMN HOLIDAY.HOLIDAY_START IS '�ް�������'
/

COMMENT ON COLUMN HOLIDAY.HOLIDAY_END IS '�ް�������'
/

ALTER TABLE HOLIDAY
    ADD CONSTRAINT FK_HOLIDAY_EMP_NUMNT_EMPLOYEE_ FOREIGN KEY (EMP_NUMNT)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE HOLIDAY
    ADD CONSTRAINT FK_HOLIDAY_APPROVAL_NUM_DOC_HO FOREIGN KEY (APPROVAL_NUM)
        REFERENCES DOC_HOLIDAY (APPROVAL_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE SALES
(
    SALES_NUM       VARCHAR2(50)    NOT NULL, 
    PRODUCT_CODE    VARCHAR2(50)    NOT NULL, 
    SALES_DATE      DATE            NOT NULL, 
    EMP_NUM         VARCHAR2(50)    NOT NULL, 
    SALES_AMOUNT    INT             NOT NULL, 
    PARTNER_NUM     VARCHAR2(50)    NOT NULL, 
    SALES_PRICE     INT             NULL, 
    CONSTRAINT SALES_PK PRIMARY KEY (SALES_NUM)
)
/

COMMENT ON TABLE SALES IS 'SALES'
/

COMMENT ON COLUMN SALES.SALES_NUM IS '�ǸŹ�ȣPST'
/

COMMENT ON COLUMN SALES.PRODUCT_CODE IS '��ǰ�ڵ�'
/

COMMENT ON COLUMN SALES.SALES_DATE IS '�Ǹ��Ͻ�'
/

COMMENT ON COLUMN SALES.EMP_NUM IS '�ǸŴ����F'
/

COMMENT ON COLUMN SALES.SALES_AMOUNT IS '�Ǹż���'
/

COMMENT ON COLUMN SALES.PARTNER_NUM IS '�ŷ�ó��ȣF'
/

COMMENT ON COLUMN SALES.SALES_PRICE IS '�Ǹűݾ�'
/

ALTER TABLE SALES
    ADD CONSTRAINT FK_SALES_PARTNER_NUM_PARTNER_P FOREIGN KEY (PARTNER_NUM)
        REFERENCES PARTNER (PARTNER_NUM)
/

ALTER TABLE SALES
    ADD CONSTRAINT FK_SALES_EMP_NUM_EMPLOYEE_EMP_ FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE SALES
    ADD CONSTRAINT FK_SALES_PRODUCT_CODE_PRODUCT_ FOREIGN KEY (PRODUCT_CODE)
        REFERENCES PRODUCT (PRODUCT_CODE)
/


-- DEPT Table Create SQL
CREATE TABLE ATTACHMENT
(
    ATT_NUM            VARCHAR2(50)      NOT NULL, 
    DOC_NUM            VARCHAR2(50)      NOT NULL, 
    ATT_ORIGIN_NAME    VARCHAR2(2000)    NOT NULL, 
    ATT_PATH           VARCHAR2(2000)    NOT NULL, 
    ATT_RENAME         VARCHAR2(50)      NOT NULL, 
    CONSTRAINT ATTACHMENT_PK PRIMARY KEY (ATT_NUM, DOC_NUM)
)
/

COMMENT ON TABLE ATTACHMENT IS '���ϰ��'
/

COMMENT ON COLUMN ATTACHMENT.ATT_NUM IS '���Ϲ�ȣPST'
/

COMMENT ON COLUMN ATTACHMENT.DOC_NUM IS '������ȣP'
/

COMMENT ON COLUMN ATTACHMENT.ATT_ORIGIN_NAME IS '���Ͽ����̸�'
/

COMMENT ON COLUMN ATTACHMENT.ATT_PATH IS '���ϰ��'
/

COMMENT ON COLUMN ATTACHMENT.ATT_RENAME IS '�����̸�ST'
/

ALTER TABLE ATTACHMENT
    ADD CONSTRAINT UC_ATT_PATH UNIQUE (ATT_PATH)
/


-- DEPT Table Create SQL
CREATE TABLE PROFILE
(
    EMP_NUM                VARCHAR2(50)      NOT NULL, 
    PROFILE_ORIGIN_NAME    VARCHAR2(2000)    NOT NULL, 
    PROFILE_PATH           VARCHAR2(2000)    NOT NULL, 
    CONSTRAINT PROFILE_PK PRIMARY KEY (EMP_NUM)
)
/

COMMENT ON TABLE PROFILE IS '�����ʻ���'
/

COMMENT ON COLUMN PROFILE.EMP_NUM IS '�����ȣPF'
/

COMMENT ON COLUMN PROFILE.PROFILE_ORIGIN_NAME IS '���Ͽ����̸�'
/

COMMENT ON COLUMN PROFILE.PROFILE_PATH IS '���ϰ��'
/

ALTER TABLE PROFILE
    ADD CONSTRAINT FK_PROFILE_EMP_NUM_EMPLOYEE_EM FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/

ALTER TABLE PROFILE
    ADD CONSTRAINT UC_PROFILE_PATH UNIQUE (PROFILE_PATH)
/


-- DEPT Table Create SQL
CREATE TABLE REFERENCE
(
    DOC_NUM    VARCHAR2(50)    NOT NULL, 
    EMP_NUM    VARCHAR2(50)    NOT NULL, 
    CONSTRAINT REFERENCE_PK PRIMARY KEY (DOC_NUM, EMP_NUM)
)
/

COMMENT ON TABLE REFERENCE IS '����'
/

COMMENT ON COLUMN REFERENCE.DOC_NUM IS '������ȣP'
/

COMMENT ON COLUMN REFERENCE.EMP_NUM IS '������PF'
/

ALTER TABLE REFERENCE
    ADD CONSTRAINT FK_REFERENCE_EMP_NUM_EMPLOYEE_ FOREIGN KEY (EMP_NUM)
        REFERENCES EMPLOYEE (EMP_NUM)
/


-- DEPT Table Create SQL
CREATE TABLE CHAT_MSG
(
    CHAT_MSG     VARCHAR2(50)      NOT NULL, 
    CHAT_ROOM    VARCHAR2(50)      NOT NULL, 
    CHAT_USER    VARCHAR2(50)      NOT NULL, 
    MSG_CONT     VARCHAR2(2000)    NOT NULL, 
    MSG_DATE     DATE              NOT NULL, 
    MSG_STAT     VARCHAR2(20)      NOT NULL, 
    CONSTRAINT CHAT_MSG_PK PRIMARY KEY (CHAT_MSG)
)
/

COMMENT ON TABLE CHAT_MSG IS '�޼���'
/

COMMENT ON COLUMN CHAT_MSG.CHAT_MSG IS '�޼��� �ĺ���ȣPST'
/

COMMENT ON COLUMN CHAT_MSG.CHAT_ROOM IS 'ä�÷��ȣ'
/

COMMENT ON COLUMN CHAT_MSG.CHAT_USER IS '�޼���������'
/

COMMENT ON COLUMN CHAT_MSG.MSG_CONT IS '�޼�������'
/

COMMENT ON COLUMN CHAT_MSG.MSG_DATE IS '���۽ð�'
/

COMMENT ON COLUMN CHAT_MSG.MSG_STAT IS '�޼�������'
/

ALTER TABLE CHAT_MSG
    ADD CONSTRAINT FK_CHAT_MSG_CHAT_ROOM_CHAT_JOI FOREIGN KEY (CHAT_ROOM, CHAT_USER)
        REFERENCES CHAT_JOIN (CHAT_ROOM, CHAT_USER)
/







--SEQ
CREATE SEQUENCE APPROVAL_NUM_SEQ;
CREATE SEQUENCE EMP_NUM_SEQ;
CREATE SEQUENCE ATT_NUM_SEQ;
CREATE SEQUENCE ATT_RENAME_SEQ;
CREATE SEQUENCE DEPT_NUM_SEQ;
CREATE SEQUENCE GRADE_NUM_SEQ;
CREATE SEQUENCE NOTICE_NUM_SEQ;
CREATE SEQUENCE DRAFT_NUM_SEQ;
CREATE SEQUENCE CONFIRM_NUM_SEQ;
CREATE SEQUENCE REQUEST_NUM_SEQ;
CREATE SEQUENCE EXPENSE_NUM_SEQ;
CREATE SEQUENCE HOLI_NUM_SEQ;
CREATE SEQUENCE SALES_NUM_SEQ;
CREATE SEQUENCE PARTNER_NUM_SEQ;
CREATE SEQUENCE LICENSE_MANAGE_SEQ;
CREATE SEQUENCE FIXTURE_NUM_SEQ;
CREATE SEQUENCE JOURN_NUM_SEQ;
CREATE SEQUENCE ACCOUNT_NUM_SEQ;
CREATE SEQUENCE PAY_NUM_SEQ;
CREATE SEQUENCE PRODUCT_CODE_SEQ;
CREATE SEQUENCE CHAT_ROOM_SEQ;
CREATE SEQUENCE CHAT_MSG_SEQ;


--TRIGGER
--CHAT_ROOM
--CREATE OR REPLACE TRIGGER TRG_CHAT_ROOM
--BEFORE INSERT ON CHAT_ROOM FOR EACH ROW
--BEGIN
--SELECT 'ROOM'||TO_CHAR(SYSDATE,'YYYYMMDD')||LPAD(CHAT_ROOM_SEQ.NEXTVAL,4,0) INTO :NEW.CHAT_ROOM FROM DUAL;
--END;
--/

--CHAT_MSG
CREATE OR REPLACE TRIGGER TRG_CHAT_MSG
BEFORE INSERT ON CHAT_MSG FOR EACH ROW
BEGIN
SELECT 'MSG'||TO_CHAR(SYSDATE,'YYYYMMDD')||LPAD(CHAT_MSG_SEQ.NEXTVAL,8,0) INTO :NEW.CHAT_MSG FROM DUAL;
END;
/
--APPROVAL
CREATE OR REPLACE TRIGGER TRG_APPROVAL
BEFORE INSERT ON APPROVAL FOR EACH ROW
BEGIN
SELECT 'APPROVAL'||TO_CHAR(SYSDATE,'YYYY')||LPAD(APPROVAL_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.APPROVAL_NUM FROM DUAL;
END;
/

--EMPLOYEE
CREATE OR REPLACE TRIGGER TRG_MEM
BEFORE INSERT ON EMPLOYEE FOR EACH ROW
BEGIN
SELECT TO_CHAR(SYSDATE,'YYYY')||LPAD(EMP_NUM_SEQ.NEXTVAL,4,0) INTO :NEW.EMP_NUM FROM DUAL;
END;
/

--ATTACHMENT ATT_NUM
CREATE OR REPLACE TRIGGER TRG_ATT
BEFORE INSERT ON ATTACHMENT FOR EACH ROW
BEGIN
SELECT 'ATT'||TO_CHAR(SYSDATE,'YYYY')||LPAD(ATT_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.ATT_NUM FROM DUAL;
END;
/

--ATTACHMENT ATT_RENAME
CREATE OR REPLACE TRIGGER TRG_ATT_RENAME
BEFORE INSERT ON ATTACHMENT FOR EACH ROW
BEGIN
SELECT 'FILE'||TO_CHAR(SYSDATE,'YYYYMMDD')||LPAD(ATT_RENAME_SEQ.NEXTVAL,4,0) INTO :NEW.ATT_RENAME FROM DUAL;
END;
/
--NOTICE
CREATE OR REPLACE TRIGGER TRG_NOTICE
BEFORE INSERT ON NOTICE FOR EACH ROW
BEGIN
SELECT 'NOTICE'||TO_CHAR(SYSDATE,'YYYY')||LPAD(NOTICE_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.NOTICE_NUM FROM DUAL;
END;
/

--DRAFT
CREATE OR REPLACE TRIGGER TRG_DRAFT
BEFORE INSERT ON DOC_DRAFT FOR EACH ROW
BEGIN
SELECT 'DRAFT'||TO_CHAR(SYSDATE,'YYYY')||LPAD(EMP_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.DRAFT_NUM FROM DUAL;
END;
/

--REQUEST
CREATE OR REPLACE TRIGGER TRG_REQUEST
BEFORE INSERT ON DOC_REQUEST FOR EACH ROW
BEGIN
SELECT 'REQ'||TO_CHAR(SYSDATE,'YYYY')||LPAD(REQUEST_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.REQUEST_NUM FROM DUAL;
END;
/

--EXPENSE
CREATE OR REPLACE TRIGGER TRG_EXPENSE
BEFORE INSERT ON DOC_EXPENSE FOR EACH ROW
BEGIN
SELECT 'EXPENSE'||TO_CHAR(SYSDATE,'YYYY')||LPAD(EXPENSE_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.EXPENSE_NUM FROM DUAL;
END;
/
--HOLLYDAY
CREATE OR REPLACE TRIGGER TRG_HOLIDAY
BEFORE INSERT ON DOC_HOLIDAY FOR EACH ROW
BEGIN
SELECT 'HOLI'||TO_CHAR(SYSDATE,'YYYY')||LPAD(HOLI_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.HOLI_NUM FROM DUAL;
END;
/
--CONFIRM
CREATE OR REPLACE TRIGGER TRG_CONFIRM
BEFORE INSERT ON CONFIRM FOR EACH ROW
BEGIN
SELECT 'CONFIRM'||TO_CHAR(SYSDATE,'YYYY')||LPAD(CONFIRM_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.CONFIRM_NUM FROM DUAL;
END;
/

--SALES
CREATE OR REPLACE TRIGGER TRG_SALES
BEFORE INSERT ON SALES FOR EACH ROW
BEGIN
SELECT 'SALES'||TO_CHAR(SYSDATE,'YYYY')||LPAD(SALES_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.SALES_NUM FROM DUAL;
END;
/
--PARTNER
CREATE OR REPLACE TRIGGER TRG_PARTNER
BEFORE INSERT ON PARTNER FOR EACH ROW
BEGIN
SELECT 'PARTNER'||TO_CHAR(SYSDATE,'YYYY')||LPAD(PARTNER_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.PARTNER_NUM FROM DUAL;
END;
/
--LICENSE
CREATE OR REPLACE TRIGGER TRG_LICENSE
BEFORE INSERT ON LICENSE FOR EACH ROW
BEGIN
SELECT 'LICENSE'||TO_CHAR(SYSDATE,'YYYY')||LPAD(LICENSE_MANAGE_SEQ.NEXTVAL,6,0) INTO :NEW.LICENSE_MANAGE FROM DUAL;
END;
/
--ACCOUNT
CREATE OR REPLACE TRIGGER TRG_ACCOUNT
BEFORE INSERT ON ACCOUNT FOR EACH ROW
BEGIN
SELECT 'ACCOUNT'||TO_CHAR(SYSDATE,'YYYY')||LPAD(ACCOUNT_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.ACCOUNT_NUM FROM DUAL;
END;
/
--PAYMENT
CREATE OR REPLACE TRIGGER TRG_PAYMENT
BEFORE INSERT ON PAYMENT FOR EACH ROW
BEGIN
SELECT 'PAYMENT'||TO_CHAR(SYSDATE,'YYYY')||LPAD(PAY_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.PAY_NUM FROM DUAL;
END;
/
--PRODUCT
CREATE OR REPLACE TRIGGER TRG_PRODUCT
BEFORE INSERT ON PRODUCT FOR EACH ROW
BEGIN
SELECT 'PRODUCT'||TO_CHAR(SYSDATE,'YYYY')||LPAD(PRODUCT_CODE_SEQ.NEXTVAL,6,0) INTO :NEW.PRODUCT_CODE FROM DUAL;
END;
/
--FIXTURE
CREATE OR REPLACE TRIGGER TRG_FIXTURE
BEFORE INSERT ON FIXTURE FOR EACH ROW
BEGIN
SELECT 'FIXTURE'||TO_CHAR(SYSDATE,'YYYY')||LPAD(FIXTURE_NUM_SEQ.NEXTVAL,6,0) INTO :NEW.FIXTURE_NUM FROM DUAL;
END;
/


--DATA
-- �μ� �Է� *�λ���, �ѹ���, �繫��, ȸ������ '�濵��������'�� ���̱� ������ ���ڸ� ��ȣ�� �����ϰ� ���ڸ��� �ٸ��ϴ�.
insert into dept values(999, '��ü�μ�');
INSERT INTO DEPT VALUES(100, 'ȸ��');
INSERT INTO DEPT VALUES(200, '��ǥ�̻�');
INSERT INTO DEPT VALUES(301, '�λ���');
INSERT INTO DEPT VALUES(302, '�ѹ���');
INSERT INTO DEPT VALUES(304, '�繫��');
INSERT INTO DEPT VALUES(305, 'ȸ����');
INSERT INTO DEPT VALUES(401, '����������');
INSERT INTO DEPT VALUES(402, '�ؿܿ�����');
INSERT INTO DEPT VALUES(500, '������');
INSERT INTO DEPT VALUES(600, 'ǰ��������');
INSERT INTO DEPT VALUES(700, 'ǰ��������');

-- ���� �Է�
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '���');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '����');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '�븮');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '����');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '����');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '����');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '�̻�');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '��');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '����');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '�λ���');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '����');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, '��ȸ��');
INSERT INTO GRADE VALUES(GRADE_NUM_SEQ.NEXTVAL, 'ȸ��');


-- ��� �Է�
-- ȸ��
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 13, 100, 150000000, '20120923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
-- ����                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�κ���', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 11, 200, 150000000, '20120923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
-- �λ���(��, ����, ����, ����, �븮, ���)                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 8, 301, 80000000, '20131001', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�����', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 301, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 301, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�Ӽ���', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 301, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            '��������α� ������1', 3, 301, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 301, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);  

-- �ѹ���(��, ����, ����, ����, �븮, ���)                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 8, 302, 80000000, '20131001', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '����ȯ', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 302, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '���¿�', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 302, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�迬��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 302, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 302, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 302, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
-- �繫��(��, ����, ����, ����, �븮, ���)                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�嵿��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 8, 304, 80000000, '20131001', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�����', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 304, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 304, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�赿��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 304, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '���ָ�', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 304, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '��â��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 304, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
-- ȸ����(��, ����, ����, ����, �븮, ���)                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '����ȯ', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 8, 305, 80000000, '20131001', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 305, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 305, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 305, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�躸��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 305, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 305, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 

-- ��������(����, ����, ����, �븮, ���)
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 401, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '���ϵ�', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 401, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 401, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 401, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 401, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 

-- �ؿܿ���(����, ����, ����, �븮, ���)
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 402, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '��â��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 402, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 402, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 402, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '����', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 402, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);                           
                            
-- ������(��, ����, ����, ����, �븮, ���)

INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�̵���', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 8, 500, 80000000, '20131001', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�嵿��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 500, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 500, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 500, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '���м�', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 500, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 500, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
-- ǰ������(��, ����, ����, ����, �븮, ���)

INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�赿��', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 8, 600, 80000000, '20131001', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 600, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '����ȯ', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 600, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 600, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '���ؼ�', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 600, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 600, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 

-- ǰ������(����, ����, ����, �븮, ���)
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '�强ȯ', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 6, 700, 50000000, '20140213', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '������', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 5, 700, 45000000, '20150703', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '���¿�', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 4, 700, 37000000, '20160923', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '����', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 3, 700, 34000000, '20170723', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT);
                            
INSERT INTO EMPLOYEE VALUES(NULL, '0901', '��Ⳳ', DEFAULT, '��', DEFAULT, DEFAULT, 
                            DEFAULT, 1, 700, 26000000, '20191123', DEFAULT, DEFAULT
                            , DEFAULT, DEFAULT); 
        

INSERT INTO EMPLOYEE VALUES(NULL, '0901', '����ö', 'gongyou@naver.com', '��', '19790710', '01024293301', 
                            '����� ������ ����ڷ�2�� 65(���｣����������) 102�� 1602ȣ', 1, 301, 28000000, '20180901', DEFAULT, DEFAULT
                            ,'110411232450', '��������');

-- ��������(�λ�301) �� �Է�
INSERT INTO NOTICE VALUES(NULL, 301, '�λ� ���� �������׿� ���� �˷��帳�ϴ�.',
                        'ȸ���� �λ� ������ [�λ�-��������] ��Ͽ��� �����Ͻ� �� ������, ���� ����� ��ü ���� �� �λ� ���õ� �����۸� ����˴ϴ�.'
                        , 20190001, SYSDATE, SYSDATE, DEFAULT, NULL);


--CHATTING DUMMY DATA
insert into chat_room values('ROOM201910250001','rName1');
insert into chat_room values('ROOM201910250002','rName2');
insert into chat_room values('ROOM201910250003','rName3');

insert into chat_join values('ROOM201910250001','empId',sysdate);
insert into chat_join values('ROOM201910250002','empId',sysdate);
insert into chat_join values('ROOM201910250003','empId',sysdate);
insert into chat_join values('ROOM201910250001','test1',sysdate);
insert into chat_join values('ROOM201910250002','test1',sysdate);
insert into chat_join values('ROOM201910250003','test2',sysdate);

insert into chat_msg values(null,'ROOM201910250001','empId','testCont',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250001','empId','testCont1',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250001','empId','testCont2',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250001','test1','testCont3',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250002','test1','���������� �ʴ��ߴ�!',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250002','test1','���������� �ʴ��ߴ�!',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250002','test1','���������� �ʴ��ߴ�!',sysdate,'Y');
insert into chat_msg values(null,'ROOM201910250003','empId','���������� �ʴ��ߴ�!',sysdate,'Y');




--�ڻ�
insert into account values(null,'����','����','1�ڻ�');
insert into account values(null,'�Ҹ�ǰ','�Ҹ�ǰ','1�ڻ�');
insert into account values(null,'�ǹ�','�ǹ�','1�ڻ�');
insert into account values(null,'������ݱ�','������ݱ�','1�ڻ�');
insert into account values(null,'����Ʈ����','����Ʈ����','1�ڻ�');

--���
insert into account values(null,'�޿�','�޿�','2���');
insert into account values(null,'�Ҹ�ǰ��','�Ҹ�ǰ��','2���');
insert into account values(null,'�����󰢺�','�����󰢺�','2���');
insert into account values(null,'�����ڻ�󰢺�','�����ڻ��','2���');
insert into account values(null,'����','����','2���');
--��ä
insert into account values(null,'������Ա�','������Ա�','3��ä');
--�ں�
insert into account values(null,'�ں���','�ں���','4�ں�');
insert into account values(null,'�����׿���','�����׿���','4�ں�');
--����
insert into account values(null,'����','����','5����');


insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('����'),100000000,
('�ں���'),100000000,null);

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('�����׿���'),0,
('�����׿���'),0,null);

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('����'),100000000,
('������Ա�'),100000000,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('�ǹ�'),100000000,
('����'),100000000 ,null);

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('������ݱ�'),10000000,
('����'),10000000,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('�Ҹ�ǰ'),1000000,
('����'),1000000,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/09/01',
('����Ʈ����'),1000000,
('����'),1000000,null );
----------------
insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/10/01',
('�޿�'),2000000,
('����'),2000000,null  );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/11/01',
('�޿�'),2000000,
('����'),2000000,null  );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/01',
('�޿�'),2000000,
('����'),2000000,null  );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/01/01',
('�޿�'),2000000,
('����'),2000000,null  );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/02/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/04/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/05/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/07/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/08/01',
('�޿�'),2000000,
('����'),2000000 ,null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/09/01',
('�޿�'),2000000,
('����'),2000000, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/10/01',
('�޿�'),2000000,
('����'),2000000, null );

--------------------�޿�ó�� ����--------------------

---------------------------------18 4/4�б�
insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/11/02',
('����'),200000000,
('����'),200000000, null );


insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('�Ҹ�ǰ��'),0,
('�Ҹ�ǰ'),0, null );


insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('�����ڻ�󰢺�'),0,
('����Ʈ����'),0, null );


insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('����'),6000000,
('�޿�'),6000000, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('����'),0,
('�Ҹ�ǰ��'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('����'),0,
('�����ڻ�󰢺�'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('����'),((select sum(credit_price) from journalizing where credit='����')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '18/10/01' and '18/12/31'))*0.15,
('����'),((select sum(credit_price) from journalizing where credit='����')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '18/10/01' and '18/12/31'))*0.15, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '18/10/01' and '18/12/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '18/10/01' and '18/12/31'))*0.15,
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '18/10/01' and '18/12/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '18/10/01' and '18/12/31'))*0.15, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('�����׿���'),((select sum(credit_price) from journalizing where credit='�����׿���')),
('�ں���'),((select sum(credit_price) from journalizing where credit='�����׿���')), null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'18/12/31',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '18/10/01' and '18/12/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '18/10/01' and '18/12/31')),
('�����׿���'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '18/10/01' and '18/12/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '18/10/01' and '18/12/31')), null );







---------------------------------19 1/4�б�
insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/02/02',
('����'),190000000,
('����'),190000000, null );


insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('�Ҹ�ǰ��'),0,
('�Ҹ�ǰ'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('�����󰢺�'),0,
('�Ҹ�ǰ��'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('�����ڻ�󰢺�'),0,
('����Ʈ����'),0, null );


insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('����'),6000000,
('�޿�'),6000000, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('����'),0,
('�Ҹ�ǰ��'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('����'),0,
('�����ڻ�󰢺�'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/01/01' and '19/03/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/01/01' and '19/03/31'))*0.15,
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/01/01' and '19/03/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/01/01' and '19/03/31'))*0.15, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/01/01' and '19/03/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/01/01' and '19/03/31'))*0.15,
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/01/01' and '19/03/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/01/01' and '19/03/31'))*0.15, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('�����׿���'),((select sum(credit_price) from journalizing where credit='�����׿���')),
('�ں���'),((select sum(credit_price) from journalizing where credit='�����׿���')), null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/03/31',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/01/01' and '19/03/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/01/01' and '19/03/31')),
('�����׿���'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/01/01' and '19/03/31')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/01/01' and '19/03/31')), null );



insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/08/31',
('����'),140000000,
('����'),140000000, null );

---------------------------------19 2/4�б�
insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/05/31',
('����'),130000000,
('����'),130000000, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('�Ҹ�ǰ��'),0,
('�Ҹ�ǰ'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('�����󰢺�'),0,
('�Ҹ�ǰ��'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('�����ڻ�󰢺�'),0,
('����Ʈ����'),0, null );


insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('����'),6000000,
('�޿�'),6000000, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('����'),0,
('�Ҹ�ǰ��'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('����'),0,
('�����ڻ�󰢺�'),0, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/04/01' and '19/06/30')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/04/01' and '19/06/30'))*0.15,
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/04/01' and '19/06/30')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/04/01' and '19/06/30'))*0.15, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/04/01' and '19/06/30')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/04/01' and '19/06/30'))*0.15,
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/04/01' and '19/06/30')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/04/01' and '19/06/30'))*0.15, null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('�����׿���'),((select sum(credit_price) from journalizing where credit='�����׿���')),
('�ں���'),((select sum(credit_price) from journalizing where credit='�����׿���')), null );

insert into journalizing values(JOURN_NUM_SEQ.nextval,'19/06/30',
('����'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/04/01' and '19/06/30')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/04/01' and '19/06/30')),
('�����׿���'),((select sum(credit_price) from journalizing where credit='����' and JOURN_DATE between '19/04/03' and '19/06/30')-(select sum(debt_price) from journalizing where debt='����' and JOURN_DATE between '19/04/01' and '19/06/30')), null );

insert into notice values(null, 305,'2018 4/4 ���Ͱ�꼭','�б� 2018 4/4', '20190001','19/01/01', '19/01/01','Y',3);
insert into notice values(null, 305,'2018 ���Ͱ�꼭','�� 2018','20190001', '19/01/01', '19/01/01','Y',3);
insert into notice values(null, 305,'2019 1/4 ���Ͱ�꼭','�б� 2019 1/4', '19/01/01', '19/01/01','Y',3);
insert into notice values(null, 305,'2019 2/4 ���Ͱ�꼭','�б� 2019 2/4', '20190001','19/01/01', '19/01/01','Y',3);
insert into notice values(null, 305,'2019-09-18 �繫����ǥ', ' 2019 09/18', '20190001','19/01/01', '19/01/01','Y',2);

insert into partner values(null, 'MS Korea','010-1111-1111','02-111-1111', '����� ���','111-1111-1111','ȫ�浿');
insert into partner values(null, 'Alpha����','010-1111-1112','02-111-1112', '����� ���','111-1111-1112','�̸���');
insert into partner values(null, '�ƾƾ�','010-1111-1113','02-111-1113', '����� ���','111-1111-1113','�Ӳ���');
insert into payment values(null, 1000000,1,'PARTNER2019000001','18/09/01','����','����');
insert into payment values(null, 1000000,1,'PARTNER2019000002','18/09/01','����','����');

insert into fixture values(null, '��Ʈ��', 'lg��Ʈ��', '18/09/01', 301, '20190001', 4,'PAYMENT2019000002');
insert into license values(null, 'mswindow', '123-123-12345', 'PAYMENT2019000001', '18/09/01' , '22/08/31', null);

insert into sales values (null,'PRODUCT2019000001','18/11/02', '20190001',20, 'PARTNER2019000003', 2000000000);
insert into sales values (null,'PRODUCT2019000001','19/02/02', '20190001',19, 'PARTNER2019000003', 1900000000);
insert into sales values (null,'PRODUCT2019000001','19/05/31', '20190001',13, 'PARTNER2019000003', 1300000000);
insert into sales values (null,'PRODUCT2019000001','19/08/31', '20190001',14, 'PARTNER2019000003', 1400000000);
insert into product values (null, '��Ѱ�', 100000000);

insert into salary values('20190001',2018, 24000000);
insert into salary values('20190001',2019, 24000000);

commit;


